"""
Voice Survey Agent — Entry Point

Starts a Pipecat bot using the official runner pattern (PipelineWorker +
WorkerRunner). Supports multiple transports (WebSocket, Daily, WebRTC)
via the `pipecat.runner.run.main()` CLI.

Usage (local dev — WebSocket transport, default):
    python -m app.main

Usage (select transport explicitly):
    python -m app.main -t websocket          # FastAPI WebSocket
    python -m app.main -t daily              # Daily WebRTC (needs DAILY_API_KEY)

Docs reference:
    https://github.com/pipecat-ai/pipecat/blob/main/examples/realtime/realtime-gemini-live.py
    (pipecat-ai/pipecat main branch, as of Aug 2026)
"""

from __future__ import annotations

import os

from dotenv import load_dotenv
from loguru import logger

from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.audio.vad.vad_analyzer import VADParams
from pipecat.frames.frames import LLMRunFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.worker import PipelineParams, PipelineWorker
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    AssistantTurnStoppedMessage,
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
    UserTurnMessageAddedMessage,
)
from pipecat.runner.types import RunnerArguments
from pipecat.runner.utils import create_transport
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.transports.websocket.fastapi import FastAPIWebsocketParams
from pipecat.workers.runner import WorkerRunner

from app.config import get_settings
from app.voice_engine import build_voice_pipeline

load_dotenv(override=True)

# Load config once at module level
settings = get_settings()

# ---------------------------------------------------------------------------
# Transport parameter map (lambdas defer creation until transport is chosen).
# The Pipecat runner selects one at runtime based on the -t flag.
# ---------------------------------------------------------------------------
transport_params = {
    "websocket": lambda: FastAPIWebsocketParams(
        audio_in_enabled=True,
        audio_out_enabled=True,
    ),
    "webrtc": lambda: TransportParams(
        audio_in_enabled=True,
        audio_out_enabled=True,
    ),
}


# ---------------------------------------------------------------------------
# Bot entrypoint — called by the Pipecat runner for each new connection.
# ---------------------------------------------------------------------------
async def run_bot(transport: BaseTransport, runner_args: RunnerArguments) -> None:
    logger.info("Starting bot — engine={}, model={}", settings.voice_engine, settings.gemini_model)

    # --- Voice engine -------------------------------------------------------
    # --- SURVEY INTEGRATION POINT ---
    # When the survey brain is ready, replace the hardcoded system prompt
    # with one generated by survey.flow.SurveyFlow based on the current
    # question from survey.json. Example:
    #
    #   from app.survey.flow import SurveyFlow
    #   survey = SurveyFlow("survey.json")
    #   system_prompt = survey.build_prompt()
    #
    voice_stages = build_voice_pipeline(
        engine=settings.voice_engine,
        config=settings,
        # system_prompt=survey.build_prompt(),  # ← uncomment when survey is ready
    )

    # Normalise to a list so the cascade engine (which returns [stt, llm, tts])
    # works without any special handling in the pipeline wiring.
    if not isinstance(voice_stages, list):
        voice_stages = [voice_stages]

    # --- Context aggregation ------------------------------------------------
    context = LLMContext()
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            vad_analyzer=SileroVADAnalyzer(params=VADParams(stop_secs=0.3)),
        ),
    )

    @user_aggregator.event_handler("on_user_turn_message_added")
    async def on_user_turn_message_added(aggregator, message: UserTurnMessageAddedMessage):
        timestamp = f"[{message.timestamp}] " if message.timestamp else ""
        logger.info("Transcript User: {}{}", timestamp, message.content)

    @assistant_aggregator.event_handler("on_assistant_turn_stopped")
    async def on_assistant_turn_stopped(aggregator, message: AssistantTurnStoppedMessage):
        timestamp = f"[{message.timestamp}] " if message.timestamp else ""
        logger.info("Transcript Assistant: {}{}", timestamp, message.content)

    # --- Pipeline -----------------------------------------------------------
    pipeline = Pipeline(
        [
            transport.input(),
            user_aggregator,
            *voice_stages,
            transport.output(),
            assistant_aggregator,
        ]
    )

    # --- SURVEY INTEGRATION POINT ---
    # When function-call tools are wired in (survey.tools), register
    # event handlers on the worker or aggregators to process tool calls.
    # Example:
    #
    #   @user_aggregator.event_handler("on_user_turn_message_added")
    #   async def on_user_msg(aggregator, message):
    #       survey.on_user_response(message)

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        idle_timeout_secs=runner_args.pipeline_idle_timeout_secs,
    )

    # --- Transport event handlers -------------------------------------------
    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")
        # Kick off the conversation — the model will greet the user.
        context.add_message(
            {"role": "user", "content": "Please introduce yourself to the user."}
        )
        await worker.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await worker.cancel()

    # --- Run ----------------------------------------------------------------
    runner = WorkerRunner(handle_sigint=runner_args.handle_sigint)
    await runner.add_workers(worker)
    await runner.run()


# ---------------------------------------------------------------------------
# Pipecat Cloud / runner compatibility
# ---------------------------------------------------------------------------
async def bot(runner_args: RunnerArguments) -> None:
    """Main bot entry point compatible with Pipecat Cloud."""
    transport = await create_transport(runner_args, transport_params)
    await run_bot(transport, runner_args)


# ---------------------------------------------------------------------------
# Local dev runner
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    from pipecat.runner.run import main

    main()
